/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PHAN_MEM;

import KETNOI_CSDL.Connection_CSDL;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import phanmemtracnghiem.frm_CauHoi;
import phanmemtracnghiem.frm_LapTaiKhoan;

/**
 *
 * @author ASUS ZENBOOK
 */
public class FormTaoDe extends javax.swing.JFrame {

    public String magv;
    private String maDeXoa = "";
    private String maDeSua = "";

    public FormTaoDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_Chinh = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnQLCauHoi = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnThemDe = new javax.swing.JButton();
        btnXoaDe = new javax.swing.JButton();
        btnSuaDe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner_TGLamBai = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenDe = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DSDeThi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DSCauHoi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_SoCauHoi = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel_Chinh.setBackground(new java.awt.Color(240, 251, 255));
        jPanel_Chinh.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 54));

        btnQLCauHoi.setBackground(new java.awt.Color(167, 217, 245));
        btnQLCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLCauHoi.setText("Quản lý câu hỏi");
        btnQLCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLCauHoiActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(167, 217, 245));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(167, 217, 245));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton3.setText("Cấp tài khoảng");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jButton3.setPreferredSize(new java.awt.Dimension(149, 39));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQLCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQLCauHoi)
                        .addComponent(btnDangXuat))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(218, 251, 249));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 54));

        btnThemDe.setBackground(new java.awt.Color(167, 217, 245));
        btnThemDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemDe.setText("Thêm đề");
        btnThemDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDeActionPerformed(evt);
            }
        });

        btnXoaDe.setBackground(new java.awt.Color(167, 217, 245));
        btnXoaDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaDe.setText("Xóa đề");
        btnXoaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDeActionPerformed(evt);
            }
        });

        btnSuaDe.setBackground(new java.awt.Color(167, 217, 245));
        btnSuaDe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaDe.setText("Sửa đề");
        btnSuaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnThemDe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnXoaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSuaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Danh sách đề thi");

        jSpinner_TGLamBai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jSpinner_TGLamBai.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Thời gian làm bài (phút)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Mã đề");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Tên đề");

        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jTable_DSDeThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đề", "Tên đề", "Thời gian", "Số câu hỏi"
            }
        ));
        jTable_DSDeThi.setShowGrid(true);
        jTable_DSDeThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DSDeThiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_DSDeThi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Danh sách câu hỏi");

        jTable_DSCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã câu hỏi", "Mã đề", "Câu thứ", "Nội dung"
            }
        ));
        jTable_DSCauHoi.setShowGrid(true);
        jScrollPane2.setViewportView(jTable_DSCauHoi);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Số câu hỏi");

        jSpinner_SoCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jSpinner_SoCauHoi.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel_ChinhLayout = new javax.swing.GroupLayout(jPanel_Chinh);
        jPanel_Chinh.setLayout(jPanel_ChinhLayout);
        jPanel_ChinhLayout.setHorizontalGroup(
            jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(jPanel_ChinhLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ChinhLayout.createSequentialGroup()
                        .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_ChinhLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_SoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_TGLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_ChinhLayout.setVerticalGroup(
            jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChinhLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtMaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jSpinner_TGLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_ChinhLayout.createSequentialGroup()
                        .addGroup(jPanel_ChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_SoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Chinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Chinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        FormDangNhap FormDangNhap = new FormDangNhap();
        FormDangNhap.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private String[] header = {"Mã đề", "Tên đề", "Thời gian","Số câu hỏi"};
    private String[] header1 = {"Mã câu hỏi", "Mã đề", "Câu thứ", "Nội dung"};
    private DefaultTableModel tableModel = new DefaultTableModel(header, 0);
    private DefaultTableModel tableModelDSCauHoi = new DefaultTableModel(header1, 0);

    public void selectDaTa() {
        Vector vector = null;
        tableModel.setRowCount(0);
        try {
            Connection c = Connection_CSDL.getConnection();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `dekiemtra`");
            while (rs.next()) {
                vector = new Vector();
                vector.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(rs.getTime(4));
                vector.add(rs.getInt(5));
                tableModel.addRow(vector);
            }
            jTable_DSDeThi.setModel(tableModel);

        } catch (SQLException ex) {
            Logger.getLogger(FormTaoDe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        selectDaTa();
    }//GEN-LAST:event_formComponentShown

    private void jTable_DSDeThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DSDeThiMouseClicked
        Vector vector = null;
        tableModelDSCauHoi.setRowCount(0);
        int soCOt=0;
         int vtDong=0;
        //soCOt = jTable_DSDeThi.getColumnCount();
        int i = 1;
        try {
            vtDong = jTable_DSDeThi.getSelectedRow();
            if (vtDong == -1) {
                JOptionPane.showMessageDialog(null, "Vị trí chọn không hợp lệ");
                return;
            }
            Object value = jTable_DSDeThi.getValueAt(vtDong, 0);
            String maDe = (String) value;
            maDeXoa = maDe;
            maDeSua= maDe.trim();
            Connection c = Connection_CSDL.getConnection();
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT cauhoi.MaCauHoi,cauhoi.MaDe,cauhoi.NoiDungCauHoi,dekiemtra.SoCauHoi FROM `dekiemtra`,`cauhoi` WHERE dekiemtra.MaDe = cauhoi.MaDe AND dekiemtra.MaDe='"+maDe+"'");
            while (rs.next()) {
                vector = new Vector();
                vector.add(rs.getString(1));
                vector.add(rs.getString(2));
                vector.add(i);
                vector.add(rs.getString(3));
                vector.add(rs.getInt(4));
                tableModelDSCauHoi.addRow(vector);
                i++;
            }
            jTable_DSCauHoi.setModel(tableModelDSCauHoi);
            btnThemDe.enable(false);

        } catch (SQLException ex) {
            Logger.getLogger(FormTaoDe.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object maDT= jTable_DSDeThi.getValueAt(vtDong, 0);
        String maDT1 = (String)maDT;
        txtMaDe.setText(maDT1);
        
        Object tenDT= jTable_DSDeThi.getValueAt(vtDong, 1);
        String tenDT1 = (String)tenDT;
        txtTenDe.setText(tenDT1);
        
        Object tgLB= jTable_DSDeThi.getValueAt(vtDong, 2);
        String tgLBString = tgLB.toString();
        LocalTime tongTG = LocalTime.parse(tgLBString);      
        int gio = tongTG.getHour();
        int phut = tongTG.getMinute();
        int tongGio = gio*60+phut;
        jSpinner_TGLamBai.setValue(tongGio);
        
        Object soCH= jTable_DSDeThi.getValueAt(vtDong, 3);
        int soCH1 = (int)soCH;
        jSpinner_SoCauHoi.setValue(soCH1);
        txtMaDe.enable(false);
        

    }//GEN-LAST:event_jTable_DSDeThiMouseClicked

    private void btnThemDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDeActionPerformed

        if (txtMaDe.getText().trim().isEmpty() || txtTenDe.getText().trim().isEmpty() || magv.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chưa nhập thông tin đề thi đầy đủ không được thêm !");
            return;
        }
        String maDe = txtMaDe.getText().trim();
        String tenDe = txtTenDe.getText().trim();
        int TGLamBai = (int) jSpinner_TGLamBai.getValue();
        int soCauHoi = (int) jSpinner_SoCauHoi.getValue();
        
        int gio=0;
        int phut=0;
        if (TGLamBai > 59) {
            gio = TGLamBai / 60;
            phut = TGLamBai % 60;
        }
        else
            phut=TGLamBai;

        LocalTime time = LocalTime.of(gio, phut, 0);

        Connection_CSDL.addData(maDe, tenDe, magv, time, soCauHoi);
        selectDaTa();

        txtMaDe.setText("");
        txtTenDe.setText("");
        jSpinner_TGLamBai.setValue(1);
        jSpinner_SoCauHoi.setValue(1);
        txtMaDe.requestFocus();
    }//GEN-LAST:event_btnThemDeActionPerformed

    private void btnXoaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDeActionPerformed

        if (maDeXoa.equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn đề cần xóa");
            return;
        }

        int result = JOptionPane.showOptionDialog(null, "Bạn có muốn xóa", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"OK", "Cancel"}, "OK");
        if (result == JOptionPane.OK_OPTION) {
            Connection_CSDL.removeData(maDeXoa);
            selectDaTa();
        } else if (result == JOptionPane.CANCEL_OPTION) {

        } else if (result == JOptionPane.CLOSED_OPTION) {

        }
        maDeXoa = "";
    }//GEN-LAST:event_btnXoaDeActionPerformed

    private void btnSuaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDeActionPerformed
        String maDe = txtMaDe.getText().trim();
        String tenDe = txtTenDe.getText().trim();
        int TGLamBai = (int) jSpinner_TGLamBai.getValue();
        int soCauHoi = (int) jSpinner_SoCauHoi.getValue();
        
        int gio=0;
        int phut=0;
        if (TGLamBai > 59) {
            gio = TGLamBai / 60;
            phut = TGLamBai % 60;
        }
        else
            phut=TGLamBai;

        LocalTime time = LocalTime.of(gio, phut, 0);
        
        Connection_CSDL.UpdateData(tenDe, time, soCauHoi, maDeSua);
        selectDaTa();
        txtMaDe.setText("");
        txtTenDe.setText("");
        jSpinner_SoCauHoi.setValue(1);
        jSpinner_TGLamBai.setValue(1);
        txtMaDe.enable(true);
    }//GEN-LAST:event_btnSuaDeActionPerformed

    private void btnQLCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLCauHoiActionPerformed
        // TODO add your handling code here:
        frm_CauHoi  fCauHoi = new frm_CauHoi();
        fCauHoi.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnQLCauHoiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frm_LapTaiKhoan fLapTaiKhoan = new frm_LapTaiKhoan();
        fLapTaiKhoan.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTaoDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTaoDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTaoDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTaoDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTaoDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLCauHoi;
    private javax.swing.JButton btnSuaDe;
    private javax.swing.JButton btnThemDe;
    private javax.swing.JButton btnXoaDe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Chinh;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner_SoCauHoi;
    private javax.swing.JSpinner jSpinner_TGLamBai;
    private javax.swing.JTable jTable_DSCauHoi;
    private javax.swing.JTable jTable_DSDeThi;
    private javax.swing.JTextField txtMaDe;
    private javax.swing.JTextField txtTenDe;
    // End of variables declaration//GEN-END:variables
}
