/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlthitracnghiem;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author ADMIN
 */
public class CauHoivaDapAn extends javax.swing.JPanel {

    private int cauThu;
    private String MaDe;
    private ButtonGroup group;
    private boolean TrangThaiDungSai = false;

    /**
     * Creates new form CauHoivaDapAn
     */
    public CauHoivaDapAn() {
        initComponents();
    }
    public int getCauThu(){
        
        return cauThu;
    }
    public boolean getTrangThaiDungSai() {
        return TrangThaiDungSai;
    }
    public void setTrangThaiDungSai(boolean trangThai) {
        TrangThaiDungSai = trangThai;
    }
    public JRadioButton getrdoCauA() {
        return rdoCauA;
    }

    public JRadioButton getrdoCauB() {
        return rdoCauB;
    }

    public JRadioButton getrdoCauC() {
        return rdoCauC;
    }

    public JRadioButton getrdoCauD() {
        return rdoCauD;
    }

    public boolean kiemTraDapAnDung(String DapAnDung, String DapAnChon) {
        if (DapAnChon.equals(DapAnDung)) {
            return true;
        }
        return false;
    }

    public CauHoivaDapAn(int cauThu, String NoiDungCau, String cau1, String cau2, String cau3, String cau4) {
        initComponents();
        this.cauThu = cauThu;
        group = new ButtonGroup();
        group.add(rdoCauA);
        group.add(rdoCauB);
        group.add(rdoCauC);
        group.add(rdoCauD);

        lbCauThu.setText("Câu " + cauThu + ": " + NoiDungCau);
        rdoCauA.setText(cau1);
        rdoCauB.setText(cau2);
        rdoCauC.setText(cau3);
        rdoCauD.setText(cau4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCauThu = new javax.swing.JLabel();
        rdoCauA = new javax.swing.JRadioButton();
        rdoCauB = new javax.swing.JRadioButton();
        rdoCauC = new javax.swing.JRadioButton();
        rdoCauD = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbCauThu.setText("Câu 1:");

        rdoCauA.setBackground(new java.awt.Color(255, 255, 255));
        rdoCauA.setText("jRadioButton1");
        rdoCauA.setName(""); // NOI18N

        rdoCauB.setBackground(new java.awt.Color(255, 255, 255));
        rdoCauB.setText("jRadioButton1");

        rdoCauC.setBackground(new java.awt.Color(255, 255, 255));
        rdoCauC.setText("jRadioButton1");

        rdoCauD.setBackground(new java.awt.Color(255, 255, 255));
        rdoCauD.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbCauThu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoCauB)
                            .addComponent(rdoCauA)
                            .addComponent(rdoCauC)
                            .addComponent(rdoCauD))))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCauThu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoCauA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoCauB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoCauC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdoCauD)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCauThu;
    private javax.swing.JRadioButton rdoCauA;
    private javax.swing.JRadioButton rdoCauB;
    private javax.swing.JRadioButton rdoCauC;
    private javax.swing.JRadioButton rdoCauD;
    // End of variables declaration//GEN-END:variables
}
